platform :ios, '14.0'

workspace 'ios/Runner.xcworkspace'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for Runner

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end